### PR TITLE
Injectionprocessor

### PR DESCRIPTION
**Pull request by andypelzer**
Hi,

first of all - I like your project a lot, thanks! Because I also liked the idea of applying aspects in broader strokes (#43), I implemented it. And more.. Aspects can now be applied to: 
- assemblies
- base classes (inherited by all child classes)
- base members (inherited by overrides)
- interfaces (inherited by child interfaces and all implementing members)
- interface members (inherited by implementing members)

I haven't implemented anything for the problem when crossing assembly boundaries you mentioned in #43 as I couldn't come up with an elegant solution yet.

Hope you like my implementation. Please don't hesitate to let me know if you don't like it and want me to change something.

### CODE REVIEW

**Comment by pamidur** [comment]
Well done! This thing is big. Would you mind us to take some time to get into it? :-)

**Comment by andypelzer** [comment]
Hi,

sure, no hurry! I think/hope it looks much bigger than it actually is.. :) Even if there are a lot of them, most commits are fairly small.

**Comment by pamidur** [comment]
Ok, I had a chance to look through changes proposed, I have some thoughts I'd like to share. Let's go one by one:
 - Aspects for assemblies - Ok!
 - Base classes (inherited by all child classes) - the thing to solve is: if we have a class A and then classes B and C that inherit class A, what would we done to class A in case class B applies aspect to base classes, and class C does not? What if that aspect is domain-wise critical, like security checking? Wouldn't we get ambiguous behavior?
 - base members (inherited by overrides) - this sounds good, however not all base members are allowed to be overwritten which might confuse developer. Also we need to ensure that we don't screw up virtual methods table in case there are classes that inherit each other and override base member as follows: abstract class A {virtual Member}, abstract class B : A {}, class C : B {overrides Member} ; and we apply aspect to class B.
 - interfaces, interface members - seem the same as base classes, isn't it? Or you mean actually applying aspects for just an interface and then look for classes that implement it?

I continue looking into changes in order to understand more, however if there is something we can't guarantee (explicit behavior, cross assembly boundaries etc) , we better not to do it.

**Comment by pamidur** [comment]
Regarding interfaces I think I've got the point: the idea is: we put aspect onto interface itself and then at a compile time we look for the classes that implement this interface and apply aspect to these classes.
Still there is a big issue; let's assume I'm a developer who code free to use library, I put aspect onto one of the public interfaces, how can I be sure that the consumer of my library also uses aspect injector so my aspect will be applied to consumer's code?

Let me put it this way:  aspect oriented stuff is for cross cutting concerns, thus it operates on a horizontal perspective. If a developer wants some functionality to be a part of vertical hierarchy he must use standard OOP approach for that. 
Please share your thoughts about it.

**Comment by andypelzer** [comment]
Hi,

I'm not really sure I understand your concern regarding base classes. My idea for base classes was that the aspects applied to base classes/members are inherited by child classes and their members, not the other way around as (I think) your example suggests. The aspect would originally be applied (in your example) to class A - and both, B and C, would inherit it. So I don't think there's ambiguity. Or am I overlooking something?

Yes, you're correct, I was applying the same principles to base classes and interfaces (and to their respective members).

To be honest my desire to allow aspects on interfaces is driven by lazyness: if I do have multiple implementers of an interface, I don't want to have to apply the same aspects to each of them, if I could apply them just once to the interface instead.. :-)

Regarding the issue of cross assembly boundaries and inheritors not being compiled with AspectInjector: as I said, I haven't found an elegant solution to this one and I actually don't think we can entirely solve (i.e. guarantee) this. But maybe an attribute applied to the inheriting assembly could help (e.g. [assembly: InheritsAspectsAttribute]) to make the inheritance explicit? That might help both ways: the inheriting assembly has to reference AspectInjector (to use the attribute), so there's no surprising implicit aspect injection happening. And it references AspectInjector (hopefully through NuGet), so it's going to be compiled with it as well. Certainly not watertight, but maybe better than nothing?

**Comment by pamidur** [comment]
Hi,

Thank you for clarification, now it is clear regarding base classes. However I still have concerns :)
 - Base classes -> Aspect put onto a class means "I want all this aspect to be injected into every member of *this* class". Implicitly inheriting aspect we implicitly apply this aspect to every member of child class. Isn't it ambiguity?
 - Interfaces -> the same for interfaces that inherit interfaces
 - Base class members -> Will we end up calling advice two (or more) times because base class still calls it? In some cases it's correct (logging method arguments), in other it's not (security check)
 - Interface members -> this is where I think your idea is the way to go. This way aspects are applied to exact implementation. Interfaces don't have implementation so it virtually says "go ahead and apply aspect to every implementation". However I'd better apply them only to explicit implementations.

Dealing with oop-inheritance we inevitably interfere with business logic, which I don't believe to be correct.

We might think of a some sort of [InheritsAspectsAttribute] which applies to every kind of member (not only assemblies), but how is that different from applying needed aspect directly?

I find all this good things to think about, we only need to find a right way to do it.
@YuriyIvon, could you please jump into conversation too?

**Comment by andypelzer** [comment]
Hi,

good points! I have to think about those for a while.. :)

With regards to the [InheritedAspectsAttribute]: I didn't intend for it to be necessary for *each member* that should inherit an aspect, just *once* for an entire assembly. Like a switch, en-/disabling inherited aspects for an assembly.

**Comment by YuriyIvon** [comment]
Hi,

If we want to apply some aspects to all classes implementing a particular interface (or extending a particular class), I would think of more explicit approach to state this intention, for example - 
add optional parameter on Aspect attribute, which specify class filter - Aspect(typeof(SomeAspect), typeof(ISomeInterface)).

At the same time, we solve the problem with necessity to add some cross-cutting functionality to all implementers of a particular interface and avoid the issues mentioned earlier.

**Comment by pamidur** [comment]
Hi,

The main idea was to mark a *base* class with Aspect (with or w/o IsInherited), that means that the consumer of the base class (developer who implements child class) might not know that **IsInherited** is claimed. Thus instead to make it explicit developer must somehow mark his *child class* in order for it to inherit base class's aspects. In that way we'll end up with [InheritedAspectsAttribute] for members.

*Wouldn't applying interface aspects only to explicit implementations make it more complex to use/understand? Why'd you like it better?* - Because explicit implementations couldn't be virtual.

**Comment by YuriyIvon** [comment]
Here is a more clear example of my proposal:
[assembly: Aspect(typeof(SomeAspect), InheritanceFilter=typeof(ISomeInterface))]
It means that SomeAspect will be injected in all classes in the current assembly which implement ISomeInterface

**Comment by andypelzer** [comment]
@YuriyIvon: I very much like that your proposal makes the scope (the current assembly) very explicit. But I'm not sure how it is going to work if you want to apply an aspect to all implementers, but only for a subset of the members of an interface.

My idea was just this:

    interface I1 
    {
        // apply SomeAspect to all implementers of I1.A but not to those of I1.B
        [Aspect(typeof(SomeAspect))]
        void A();
        void B();
    }

    class A : I1
    {
        public void A() {} // has aspect 
        public void B() {} // does not have aspect
    }

    class B : I1
    {
        public void A() {} // has aspect 
        public void B() {} // does not have aspect
    }

But this of course would not limit the scope to a set of implementers (e.g. an assembly). This definitely isn't as easy as I originally thought.. :)

**Comment by andypelzer** [comment]
@pamidur: I've thought a bit about duplicate aspect invocations when calling overrides and I may have come up with a solution. Either the base method was abstract, then there should only be an invocation of the aspect for the overriding method in the child class. In case the base method was virtual, the implementation of the child method decides: if there is a base call, then the aspect is invoked for the base method as well as the child method, if there is none, then it is only invoked for the child method.

```
abstract class A
{
    [Aspect(typeof(SomeAspect)]
    abstract void M1();

    [Aspect(typeof(SomeAspect)]
    virtual void M2() {}

    [Aspect(typeof(SomeAspect)]
    virtual void M3() {}
}

class B : A
{
    // invokes SomeAspect once, only for B.M1()
    override void M1() {}

    // invokes SomeAspect once, only for B.M2()
    override void M2() {}

    // invokes SomeAspect twice, once for B.M3() and once for A.M3()
    override void M3() 
    {
        base.M3();
    }
}
```

What do you think?

**Comment by pamidur** [comment]
Hi,

@andypelzer your solution to duplicate calls makes sense. It is easier with base methods because developer explicitly says *override*. Need to think about interface's members.
However we still need to find a way for consumer to explicitly allow inheritance.
```c#
assembly 1:
abstract class A
{
    [Aspect(typeof(EnforceHighSecurity)] //really high security  :)
    virtual void M1() {}
}

assembly 2:
class B : A
{
    //as a consumer, how do I allow this method to inherit base class' security mechanism?
    //applying it w/o my awareness can easily screw everything up
    override void M1() {}
}
```

Remember: Aspects may prevent original method from execution.

**Comment by andypelzer** [comment]
Hi,

I still haven't come up with a solution for explicit inheritance that does not weaken/destroy the advantage of not having to repeat yourself. But I think a consumer (child class) only needs to declare its intent to inherit aspects **once** to remove the element of surprise. 

So maybe something like an InheritsAspects attribute applied to child classes would fulfill both needs?

```cs
abstract class A
{
    [Aspect(typeof(SomeAspect)]
    abstract void M1();
}

[Aspect(typeof(SomeOtherAspect)]
abstract class B : A
{
    virtual void M2() {}
}

[Aspect(typeof(SomeThirdAspect)]
interface I1
{
    void M3();
}

interface I2
{
    [Aspect(typeof(SomeAspect)]
    void M4();

    void M5();
}

[InheritsAspects]
class C : B, I1, I2
{
    // child call invokes SomeAspect
    // because C derives from B, SomeOtherAspect will be invoked as well
    override void M1()
    {
        base.M1(); // base call invokes SomeAspect
    }

    // M2 is not overridden, so base behavior applies (i.e. SomeOtherAspect will be invoked)

    // part of I1, so SomeThirdAspect will be invoked
    // because C derives from B, SomeOtherAspect will be invoked as well
    void M3() {}

    // implements I2.M4, so SomeAspect is invoked
    // because C derives from B, SomeOtherAspect will be invoked as well
    void M4() {}

    // only SomeOtherAspect will be invoked (because C derives from B)
    void M5() {}
}
```

What do you think?

**Comment by YuriyIvon** [comment]
@andypelzer: there are already capabilities to apply an aspect only to particular methods - there are attributes NameFilter and AccessModifierFilter on the Aspect attribute, so my example can be rewritten as:
```
[assembly: Aspect(typeof(SomeAspect), InheritanceFilter=typeof(ISomeInterface), NameFilter="A")]
```
obviously, that doesn't prevent issues with renames, however I would say that applying an aspect only to a particular interface member doesn't seem a good practice to me. I can see good practical sense in applying an aspect to all implementers of an interface (according to the rules contained inside the aspect itself), but covering only particular methods is more difficult to track and, in general, gives some "special" meaning to some interface members. Perhaps in such cases it would be better to extract such members to a separate interface.

**Comment by pamidur** [comment]
@YuriyIvon I'd say
 InheritanceFilter=new[] { typeof(ISomeInterface) }

I think this is right way to implement it. So: 
- Make AspectAttribute apply to an assembly
- Add brand new InheritanceFilter, where if not specified treated as "Do nothing with inherited members"
- Implement proxy creation for base members

One more thing what would we do with sealed members?

**Comment by pamidur** [comment]
Nope, still no good:
```c#
assembly 1:

[Aspect(typeof(MyAspect))]
class MyBaseClass
{
    protected virtual void Do()
    {
    }
}

```
and then

```c#
assembly 2:

[assembly: Aspect(typeof(MyAspect), InheritanceFilter=typeof(MyBaseClass))]

class MyClass : MyBaseClass
{
    protected override void Do()
    {
    }
}
```

So I have to specify `typeof(MyAspect)` two times. One for original class, one for assembly that contains subclasses? This way I don't even really need to put aspect on my base class.
I'm ok with `[assembly: Aspect(typeof(MyAspect), InheritanceFilter=typeof(MyBaseClass))]` if it means - "find descendant classes in this assembly and apply MyAspect to their (only inherited?) members"

**Comment by pamidur** [comment]
We need to rethink this

**Pull request closed without merging**
